# Generated by Django 3.1.5 on 2021-01-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.IntegerField(default=0)),
                ('cylinderSize', models.CharField(choices=[('S', '2 x 2'), ('M', '4 x 10'), ('L', '6 x 12')], max_length=1)),
            ],
        ),
    ]
