# Generated by Django 3.1.5 on 2021-01-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='serialNo',
            field=models.CharField(max_length=25),
        ),
    ]
